function [ hotspotArguments, Pdyn, leakage ] = configure
  path = File.join(File.trace, '..', 'Assets');

  floorplan = File.join(path, '04.flp');
  hotspotArguments = { ...
    floorplan, ...
    File.join(path, 'hotspot.config'), ...
    'sampling_intvl 1e-3' };

  powerProfile = File.join(path, '04.ptrace');
  Pdyn = 2 * dlmread(powerProfile, '', 1, 0).';

  leakageFilename = File.join(path, 'inverter_45nm.leak');
  leakage = LeakagePower(Pdyn, ...
    'filename', leakageFilename, ...
    'order', [ 1, 2 ], ...
    'scale', [ 1, 1, 1; 1, 1, 1 ]);
end
