function scaleSteps
  compareSpeed( ...
    'name', 'Number of steps', ...
    'shortName', 'Steps', ...
    'range', [ 1e2 1e3 1e4 1e5 1e6 ], ...
    'configure', @(stepCount) configure( ...
      'processorCount', 4, 'stepCount', stepCount));
end