setup;

fontName = 'CMU_Sans_Serif';

order = 1:5;

exp = [  0.44  0.16 0.14 0.13 0.13 ];
var = [ 36.92 14.97 6.32 3.01 1.72 ];
pdf = [  8.80  6.33 3.07 1.74 1.59 ];

figure;

line(order, exp, ...
  'Color', Color.pick(1), ...
  'LineWidth', 2, 'Marker', 'v', 'MarkerSize', 8);

line(order, var, ...
  'Color', Color.pick(2), ...
  'LineWidth', 2, 'Marker', 's', 'MarkerSize', 8);

line(order, pdf, ...
  'Color', Color.pick(3), ...
  'LineWidth', 2, 'Marker', 'o', 'MarkerSize', 8);

set(gca, 'XTick', order);

set(gca, ...
  'FontName', fontName, ...
  'FontSize', 14);

legend('Expectation', 'Variance', 'PDF');

title('Error Measurements', ...
  'FontName', fontName, ...
  'FontSize', 20, ...
  'FontWeight', 'normal');

xlabel('Polynomial order', ...
  'FontName', fontName, ...
  'FontSize', 16);

ylabel('Error, %', ...
  'FontName', fontName, ...
  'FontSize', 16);